### ISSUE TITLE
RedisClient does not return any response

### ISSUE THREAD

**Issue by ugrcnkaya** [Lakusan/ACS_ADB#1]
redis client connection does not return any error or success message. There is even no time out after waiting for minutes.

**Comment by Lakusan** [comment]
Changed to Ubuntu 20.04 with orginal package.json. 

See Branch: al_hf_redis_connection

with connect() => redisClient.on('connect', () => console.log('Connected to redis server'));  gets executed.

**Comment by Lakusan** [comment]
Depenends on the Error Handling and calling method, we need to explicitly get the ok after pushing date to redis, because there is no accept or ack callback. At least I didn't find anything about that. 
Adding Data to Redis works. Getting Data not at the moment.

**Comment by Lakusan** [comment]
![image](https://github.com/Lakusan/ACS_ADB/assets/47719054/20ebc7d9-1312-431d-a918-1065d04c3e27)

**Comment by ugrcnkaya** [comment]
Installed server on docker container,
for each of the method like get, setEx etc there should be different client object instance. 

one instance can not be used for multiple times.
